<a href="https://colab.research.google.com/github/KeysiYTS/pandas-exercises/blob/main/Python_Pandas_Data_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[W3 Resources](https://www.w3resource.com/python-exercises/pandas/index-data-series.php)


In [1]:
import pandas as pd
import numpy as np

# OCT-01-2021

## 1- Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

oct-01-2021

In [ ]:
pds = pd.Series(data=[1,2,3,4,5])
print(pds)

0    1
1    2
2    3
3    4
4    5
dtype: int64


##2- Write a Pandas program to convert a Panda module Series to Python list and it's type

In [ ]:
python_list = pds.to_list()
print(python_list)

[1, 2, 3, 4, 5]


In [ ]:
print(type(pds.to_list()))

<class 'list'>


## 3- Write a Pandas program to add, subtract, multiple and divide two Pandas Series. 


In [ ]:
# Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
pds1 = pd.Series(data=[2, 4, 6, 8, 10])
pds2 = pd.Series(data=[1, 3, 5, 7, 9])

In [ ]:
pds_add = pds1.add(pds2, axis=0) # or pds1 + pds2
print(pds_add)

0     3
1     7
2    11
3    15
4    19
dtype: int64


In [ ]:
pds_sub = pds1.subtract(pds2, axis=0) # or pds1 - pds2
print(pds_sub)

0    1
1    1
2    1
3    1
4    1
dtype: int64


In [ ]:
pds_mul = pds1.multiply(pds2, axis=0) # or pds1 * pds2
print(pds_mul)

0     2
1    12
2    30
3    56
4    90
dtype: int64


In [ ]:
pds_div = pds1.divide(pds2, axis=0) # or pds1/pds2
print(pds_div)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


## 4- Write a Pandas program to compare the elements of the two Pandas Series.


In [ ]:
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
pds1 = pd.Series(data=[2, 4, 6, 8, 10])
pds2 = pd.Series(data=[1, 3, 5, 7, 10])

In [ ]:
print(pds1 == pds2)

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [ ]:
print(pds1 > pds2)

0     True
1     True
2     True
3     True
4    False
dtype: bool


In [ ]:
print(pds1 < pds2)

0    False
1    False
2    False
3    False
4    False
dtype: bool


## 5- Write a Pandas program to convert a dictionary to a Pandas series. 

In [ ]:
"""
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64
"""

"\nSample Series:\nOriginal dictionary:\n{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}\nConverted series:\na 100\nb 200\nc 300\nd 400\ne 800\ndtype: int64\n"

In [ ]:
pds = pd.Series(data={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})
print(pds)

a    100
b    200
c    300
d    400
e    800
dtype: int64


## 6- Write a Pandas program to convert a NumPy array to a Pandas series.

In [ ]:
"""
Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64
"""

'\nSample Series:\nNumPy array:\n[10 20 30 40 50]\nConverted Pandas series:\n0 10\n1 20\n2 30\n3 40\n4 50\ndtype: int64\n'

In [ ]:
npa = np.array([10, 20, 30, 40, 50])
print(npa)
print(type(npa))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
pdn = pd.Series(data=npa)
print(pdn)

0    10
1    20
2    30
3    40
4    50
dtype: int64


## !!7- Write a Pandas program to change the data type of given a column or a Series. 

In [ ]:
"""
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64
"""

'\nSample Series:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nChange the said data type to numeric:\n0 100.00\n1 200.00\n2 NaN\n3 300.12\n4 400.00\ndtype: float64\n'

In [ ]:
pds = pd.Series(data=[100,200,'python',300.12,400])
print(pds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [ ]:
pd.to_numeric(pds, errors='coerce')

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

## 8- Write a Pandas program to convert the first column of a DataFrame as a Series.

In [ ]:
"""
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>
"""

"\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\n1st column as a Series:\n0 1\n1 2\n2 3\n3 4\n4 7\n5 11\nName: col1, dtype: int64\n<class 'pandas.core.series.Series'>\n"

In [ ]:
arrays = [[1 ,4 ,7], [2 ,5 ,5],
          [3 ,6 ,8], [4 ,9 ,12],
          [7 ,5 ,1], [11, 0, 11]]

In [ ]:
pdf = pd.DataFrame(data=arrays, columns=['col1','col2','col3'])
pdf

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [ ]:
print(pdf['col1'])
print(type(pdf['col1']))

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


## !!9- Write a Pandas program to convert a given Series to an array.

In [ ]:
"""
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
"""

"\nSample Output:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nSeries to an array\n['100' '200' 'python' '300.12' '400']\n"

In [ ]:
pds = pd.Series(data=[100,200,'python',300.12,400])
print(pds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [ ]:
pds.to_list()

[100, 200, 'python', 300.12, 400]

## ?10- Write a Pandas program to convert Series of lists to one Series.

In [ ]:
"""
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object
"""

'\nSample Output:\nOriginal Series of list\n0 [Red, Green, White]\n1 [Red, Black]\n2 [Yellow]\ndtype: object\nOne Series\n0 Red\n1 Green\n2 White\n3 Red\n4 Black\n5 Yellow\ndtype: object\n'

## 11 - Write a Pandas program to sort a given Series

In [ ]:
"""
Sample Output:
Original Data Series: 
0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object
"""

'\nSample Output:\nOriginal Data Series: \n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\n0 100\n1 200\n3 300.12\n4 400\n2 python\ndtype: object\n'

In [ ]:
pds = pd.Series(['100', '200', 'python', '300.12', '400'])
pds

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [ ]:
pds.sort_values()

0       100
1       200
3    300.12
4       400
2    python
dtype: object

# OCT-02-2021

## !!12- Write a Pandas program to add some data to an existing Series. 




In [ ]:
"""
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object
"""

'\nSample Output:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nData Series after adding some data:\n0 100\n1 200\n2 python\n3 300.12\n4 400\n0 500\n1 php\ndtype: object\n'

In [ ]:
pds = pd.Series(['100', '200', 'python', '300.12', '400'])
pds

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [ ]:
pds.append(to_append=pd.Series(['500', 'php']))

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

## 13- Write a Pandas program to create a subset of a given series based on value and condition.

In [ ]:
"""
Sample Output:
Original Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64
"""

'\nSample Output:\nOriginal Data Series:\n0 0\n1 1\n2 2\n3 3\n4 4\n5 5\n6 6\n7 7\n8 8\n9 9\n10 10\ndtype: int64\nSubset of the above Data Series:\n0 0\n1 1\n2 2\n3 3\n4 4\n5 5\ndtype: int64\n'

In [ ]:
var = [0,1,2,3,4,5,6,7,8,9,10]

In [ ]:
pds = pd.Series(data=var)
pds

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [ ]:
pds.iloc[0:6]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

## !!14- Write a Pandas program to change the order of index of a given series. 

In [ ]:
"""
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64
"""

'\nSample Output:\nOriginal Data Series:\nA 1\nB 2\nC 3\nD 4\nE 5\ndtype: int64\nData Series after changing the order of index:\nB 2\nA 1\nC 3\nD 4\nE 5\ndtype: int64\n'

In [ ]:
var = [1,2,3,4,5]
idx = ['A', 'B', 'C', 'D', 'E']

In [ ]:
pds = pd.Series(var, index=idx)
pds

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [ ]:
idx2 = ['B', 'A', 'C', 'D', 'E']

In [ ]:
pds.reindex(index=idx2)

B    2
A    1
C    3
D    4
E    5
dtype: int64

## 15- Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [ ]:
"""
Sample Output:
Original Data Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565
"""

'\nSample Output:\nOriginal Data Series:\n0 1\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n7 8\n8 9\n9 5\n10 3\ndtype: int64\nMean of the said Data Series:\n4.818181818181818\nStandard deviation of the said Data Series:\n2.522624895547565\n'

In [ ]:
var = [1,2,3,4,5,6,7,8,9,5,3]

In [ ]:
pds = pd.Series(data=var)

In [ ]:
pds.mean()

4.818181818181818

In [ ]:
pds.std()

2.522624895547565

# OCT-07-2021

### !!16- Write a Pandas program to get the items of a given series not present in another given serieS

In [ ]:
"""
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64
"""

'\nOriginal Series:\nsr1:\n0 1\n1 2\n2 3\n3 4\n4 5\ndtype: int64\nsr2:\n0 2\n1 4\n2 6\n3 8\n4 10\ndtype: int64\nItems of sr1 not present in sr2:\n0 1\n2 3\n4 5\ndtype: int64\n'

In [ ]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]

In [ ]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

In [ ]:
pd_sr1[~pd_sr1.isin(pd_sr2)]

0    1
2    3
4    5
dtype: int64

In [ ]:
pd_sr1[pd_sr1.isin(pd_sr2) == False]

0    1
2    3
4    5
dtype: int64

## ?17- Write a Pandas program to get the items which are not common of two given series.

In [ ]:
"""
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of a given series not present in another given series:
0 1
2 3
4 5
5 6
6 8
7 10
dtype: int64
"""

'\nSample Output:\nOriginal Series:\nsr1:\n0 1\n1 2\n2 3\n3 4\n4 5\ndtype: int64\nsr2:\n0 2\n1 4\n2 6\n3 8\n4 10\ndtype: int64\nItems of a given series not present in another given series:\n0 1\n2 3\n4 5\n5 6\n6 8\n7 10\ndtype: int64\n'

In [ ]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]

In [ ]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

## !!18- Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
3 8.990256
4 13.925283
5 12.056875
.... 17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]
"""

'\nSample Output:\nOriginal Series:\n0 3.000938\n1 11.370722\n2 14.612143\n3 8.990256\n4 13.925283\n5 12.056875\n.... 17 14.118931\n18 8.247458\n19 5.526727\ndtype: float64\nMinimum, 25th percentile, median, 75th, and maximum of a given series:\n[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]\n'

In [ ]:
sr = [3.000938,11.370722,14.612143,8.990256,13.925283,12.056875]

In [ ]:
pd_sr = pd.Series(data=sr)
pd_sr

0     3.000938
1    11.370722
2    14.612143
3     8.990256
4    13.925283
5    12.056875
dtype: float64

In [ ]:
print(pd_sr.min())
print(pd_sr.median())
print(pd_sr.max())

3.000938
11.7137985
14.612143


In [ ]:
np.percentile(pd_sr, q=[0,25,50,100])

array([ 3.000938 ,  9.5853725, 11.7137985, 14.612143 ])

In [ ]:
result = np.percentile(pd_sr, q=[0,25,50,75,100])
print(f'Min. value: {result[0]}')
print(f"25th percentile: {result[1]}")
print(f"median: {result[2]}")
print(f"75th percentile: {result[3]}")
print(f"max value: {result[4]}")

Min. value: 3.000938
25th percentile: 9.5853725
median: 11.7137985
75th percentile: 13.458181
max value: 14.612143


# OCT-08-2021


## 19- Write a Pandas program to calculate the frequency counts of each unique value of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 1
1 7
2 1
3 6
4 9
5 1
... 29 2
30 9
31 1
32 2
33 9
34 2
35 9
36 0
37 0
38 4
39 8
dtype: object
Frequency of each unique value of the said series.
0 9
2 7
9 6
1 5
6 3
8 3
7 3
3 2
4 1
5 1
dtype: int64s
"""

'\nSample Output:\nOriginal Series:\n0 1\n1 7\n2 1\n3 6\n4 9\n5 1\n... 29 2\n30 9\n31 1\n32 2\n33 9\n34 2\n35 9\n36 0\n37 0\n38 4\n39 8\ndtype: object\nFrequency of each unique value of the said series.\n0 9\n2 7\n9 6\n1 5\n6 3\n8 3\n7 3\n3 2\n4 1\n5 1\ndtype: int64s\n'

In [ ]:
sr = [1,16,5,1,8,4,18,4,8,7,9,4,5,1,6,8,76,1,56,49,8]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr.value_counts() 

8     4
1     4
4     3
5     2
56    1
18    1
49    1
16    1
76    1
9     1
7     1
6     1
dtype: int64

## ??20- Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series. 

In [ ]:
sr = np.random.randint(1,20,[20])

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
value_frequency = pd_sr.value_counts()
value_frequency

9     4
4     3
17    2
11    2
10    2
1     2
16    1
15    1
12    1
3     1
2     1
dtype: int64

In [ ]:
value_frequency.replace()

9     4
4     3
17    2
11    2
10    2
1     2
16    1
15    1
12    1
3     1
2     1
dtype: int64

In [ ]:
pd_sr[pd_sr.isin(value_frequency)]

0     1
5     4
7     3
10    2
14    4
15    4
19    1
dtype: int64

In [ ]:
pd_sr

0      1
1     11
2      9
3     12
4      9
5      4
6      9
7      3
8     11
9     16
10     2
11    17
12    15
13    17
14     4
15     4
16    10
17    10
18     9
19     1
dtype: int64

In [ ]:
value_frequency

9     4
4     3
17    2
11    2
10    2
1     2
16    1
15    1
12    1
3     1
2     1
dtype: int64

# OCT-11-2021


## !!21- Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series

In [ ]:
"""
Original Series:
0 1
1 9
2 8
3 6
4 9
5 7
6 1
7 1
8 1
dtype: int64
Positions of numbers that are multiples of 5:
[]
"""

'\nOriginal Series:\n0 1\n1 9\n2 8\n3 6\n4 9\n5 7\n6 1\n7 1\n8 1\ndtype: int64\nPositions of numbers that are multiples of 5:\n[]\n'

In [ ]:
sr = [9,1,8,5,9,7,1,1,1]

In [ ]:
pd_sr = pd.Series(data=sr)
pd_sr

0    9
1    1
2    8
3    5
4    9
5    7
6    1
7    1
8    1
dtype: int64

Find the indices of array elements that are non-zero, grouped by element.

In [ ]:
pd_sr[pd_sr%5==0].index

Int64Index([3], dtype='int64')

OR

In [ ]:
values = np.random.randint(1,20,15)
pd_np_sr = pd.Series(values)
print(pd_np_sr)
print(np.argwhere(values%5==0))

0     14
1     17
2     13
3      8
4      5
5     19
6      2
7     13
8     10
9      3
10    16
11    18
12     1
13    18
14     3
dtype: int64
[[4]
 [8]]


## !!22- Write a Pandas program to extract items at given positions of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 2
1 3
2 9
3 0
4 2
5 3
... 19 0
20 2
21 3
dtype: object
Extract items at given positions of the said series:
0 2
2 9
6 8
11 0
21 3
dtype: object
"""

'\nSample Output:\nOriginal Series:\n0 2\n1 3\n2 9\n3 0\n4 2\n5 3\n... 19 0\n20 2\n21 3\ndtype: object\nExtract items at given positions of the said series:\n0 2\n2 9\n6 8\n11 0\n21 3\ndtype: object\n'

In [ ]:
values = np.random.randint(1, 20, 15)

In [ ]:
pd_sr = pd.Series(values)

In [ ]:
pd_sr.take([0,2,6,11])

0     17
2      5
6      7
11     6
dtype: int64

In [ ]:
pd_sr[0:12]

0     17
1     15
2      5
3     18
4     11
5     11
6      7
7      5
8      7
9      8
10    10
11     6
dtype: int64

## 23- Write a Pandas program to get the positions of items of a given series in another given series.

In [ ]:
"""
Sample Output:
Original Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 1
1 3
2 5
3 7
4 10
dtype: int64
Positions of items of series2 in series1:
[0, 2, 4, 6, 9]
"""

'\nSample Output:\nOriginal Series:\n0 1\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n7 8\n8 9\n9 10\ndtype: int64\n0 1\n1 3\n2 5\n3 7\n4 10\ndtype: int64\nPositions of items of series2 in series1:\n[0, 2, 4, 6, 9]\n'

In [ ]:
sr1 = [1,2,3,4,5,6,7,8,9,10]
sr2 = [1,3,5,7]

In [ ]:
pd_sr1 = pd.Series(sr1)
pd_sr2 = pd.Series(sr2)

In [ ]:
pd_sr2[pd_sr2 == 3].index[0]

1

In [ ]:
indexes = []
for value in pd_sr2:
  if value in pd_sr1:
    index  = pd_sr1[pd_sr1 == value].index[0]
    indexes.append(index)

In [ ]:
indexss = [pd_sr1[pd_sr1 == value].index[0] for value in pd_sr2 if value in pd_sr1]

In [ ]:
indexes

[0, 2, 4, 6]

In [ ]:
indexss

[0, 2, 4, 6]

# OCT-13-2021

## ??24- Write a Pandas program convert the first and last character of each word to upper case in each word of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 php
1 python
2 java
3 c#
dtype: object
First and last character of each word to upper case:
0 PhP
1 PythoN
2 JavA
3 C#
dtype: object
"""

'\nSample Output:\nOriginal Series:\n0 php\n1 python\n2 java\n3 c#\ndtype: object\nFirst and last character of each word to upper case:\n0 PhP\n1 PythoN\n2 JavA\n3 C#\ndtype: object\n'

In [ ]:
sr = ['php','python','java','c#']
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr

0       php
1    python
2      java
3        c#
dtype: object

## !!25- Write a Pandas program to calculate the number of characters in each word in a given series.

In [ ]:
sr = ['php','python','java','c#']
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr.map(lambda x: len(x))

0    3
1    6
2    4
3    2
dtype: int64

## !!26- Write a Pandas program to compute difference of differences between consecutive numbers of a given series. 

In [ ]:
"""
Sample Output:
Original Series:
0 1
1 3
2 5
3 8
4 10
5 11
6 15
dtype: int64
Difference of differences between consecutive numbers of the said series:
[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]
[nan, nan, 0.0, 1.0, -1.0, -1.0, 3.0]
"""

In [ ]:
sr = [1,3,5,8,10,11,15]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr.diff()

0    NaN
1    2.0
2    2.0
3    3.0
4    2.0
5    1.0
6    4.0
dtype: float64

In [ ]:
pd_sr.diff().diff()

0    NaN
1    NaN
2    0.0
3    1.0
4   -1.0
5   -1.0
6    3.0
dtype: float64

## 27- Write a Pandas program to convert a series of date strings to a timeseries

In [ ]:
"""
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Series of date strings to a timeseries:
0 2015-01-01 00:00:00
1 2016-10-02 00:00:00
2 2018-03-07 00:00:00
3 2014-05-06 00:00:00
4 2016-04-12 00:00:00
5 2019-04-06 11:20:00
dtype: datetime64[ns]
"""

'\nOriginal Series:\n0 01 Jan 2015\n1 10-02-2016\n2 20180307\n3 2014/05/06\n4 2016-04-12\n5 2019-04-06T11:20\ndtype: object\nSeries of date strings to a timeseries:\n0 2015-01-01 00:00:00\n1 2016-10-02 00:00:00\n2 2018-03-07 00:00:00\n3 2014-05-06 00:00:00\n4 2016-04-12 00:00:00\n5 2019-04-06 11:20:00\ndtype: datetime64[ns]\n'

In [ ]:
sr = ["01 Jan 2015", "10-02-2016", "20180307", "2014/05/06", "2016-04-12", "2019-04-06T11:20"]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [ ]:
pd_sr = pd.to_datetime(pd_sr)
pd_sr

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

# OCT-14-2021

## !!28- Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings. 

In [ ]:
"""
Sample Output:
Original Series:
0 01 Jan 2015
1 10-02-2016
2 20180307
3 2014/05/06
4 2016-04-12
5 2019-04-06T11:20
dtype: object
Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of week:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']
"""

In [ ]:
sr = ["01 Jan 2015", "10-02-2016", "20180307", "2014/05/06", "2016-04-12", "2019-04-06T11:20"]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr_date = pd.to_datetime(pd_sr)

In [ ]:
pd_sr_date

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [ ]:
import datetime as dt

In [ ]:
pd_sr_date.dt.day.to_list()

[1, 2, 7, 6, 12, 6]

In [ ]:
pd_sr_date.dt.weekday.to_list()

[3, 6, 2, 1, 1, 5]

In [ ]:
pd_sr_date.dt.month.to_list()

[1, 10, 3, 5, 4, 4]

In [ ]:
pd_sr_date.dt.isocalendar().week.to_list()

[1, 39, 10, 19, 15, 14]

In [ ]:
pd_sr_date.dt.day_name().to_list()

['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']

## 29- Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [ ]:
"""
Sample Output:
Original Series:
0 Jan 2015
1 Feb 2016
2 Mar 2017
3 Apr 2018
4 May 2019
dtype: object
New dates:
0 2015-01-11
1 2016-02-11
2 2017-03-11
3 2018-04-11
4 2019-05-11
dtype: datetime64[ns]
"""

'\nSample Output:\nOriginal Series:\n0 Jan 2015\n1 Feb 2016\n2 Mar 2017\n3 Apr 2018\n4 May 2019\ndtype: object\nNew dates:\n0 2015-01-11\n1 2016-02-11\n2 2017-03-11\n3 2018-04-11\n4 2019-05-11\ndtype: datetime64[ns]\n'

In [ ]:
sr = ["Jan 2015", "Feb 2016","Mar 2017","Apr 2018","May 2019"]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr

0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

In [ ]:
pd.to_datetime(pd_sr)

0   2015-01-01
1   2016-02-01
2   2017-03-01
3   2018-04-01
4   2019-05-01
dtype: datetime64[ns]

# OCT-15-2021

## ??30- Write a Pandas program to filter words from a given series that contain atleast two vowels. 

In [ ]:
"""
Original Series:
0 Red
1 Green
2 Orange
3 Pink
4 Yellow
5 White
dtype: object
Filtered words:
1 Green
2 Orange
4 Yellow
5 White
dtype: object
"""

In [ ]:
sr = ["Red","Green","Orange","Pink","Yellow","White"]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
words = [string for string in pd_sr if len(string) > 3]

In [ ]:
words

['Green', 'Orange', 'Pink', 'Yellow', 'White']

In [ ]:
wrd_sr = pd.Series(data=words)

In [ ]:
wrd_sr

0     Green
1    Orange
2      Pink
3    Yellow
4     White
dtype: object

## !! 31-Write a Pandas program to compute the Euclidean distance between two given series.

Euclidean distance
From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.

In [ ]:
"""
Original series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 11
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Euclidean distance between two said series:
16.492422502470642
"""

In [ ]:
sr1 = [1,2,3,4,5,6,7,8,9,10]
sr2 = [11,8,7,5,6,5,3,4,7,1]

In [ ]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

In [ ]:
np.linalg.norm(pd_sr1 - pd_sr2)

16.492422502470642

## 32- Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [ ]:
"""
Original series:
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Positions of the values surrounded by smaller values on both sides:
[1 4 8]
"""

In [ ]:
sr = [1,8,7,5,6,5,3,4,7,1]
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr.diff()

0    NaN
1    7.0
2   -1.0
3   -2.0
4    1.0
5   -1.0
6   -2.0
7    1.0
8    3.0
9   -6.0
dtype: float64

In [ ]:
np.diff(pd_sr)

array([ 7, -1, -2,  1, -1, -2,  1,  3, -6])

In [ ]:
np.sign(np.diff(pd_sr))

array([ 1, -1, -1,  1, -1, -1,  1,  1, -1])

In [ ]:
temp = np.diff(np.sign(np.diff(pd_sr)))
temp

array([-2,  0,  2, -2,  0,  2,  0, -2])

# OCT-18-2021

## !!33- Write a Pandas program to replace missing white spaces in a given string with the least frequent character.

In [ ]:
"""
Original series:
abc def abcdef icd
c 3
d 3
3
b 2
e 2
a 2
f 2
i 1
dtype: int64
abcidefiabcdefiicd
"""

In [5]:
sr ='abc def abcdef icd'
pd_sr = pd.Series(data=list(sr))

In [8]:
pd_sr

0     a
1     b
2     c
3      
4     d
5     e
6     f
7      
8     a
9     b
10    c
11    d
12    e
13    f
14     
15    i
16    c
17    d
dtype: object

In [6]:
pd_sr.value_counts()

d    3
c    3
     3
f    2
b    2
e    2
a    2
i    1
dtype: int64

In [9]:
element_frq = pd_sr.value_counts()

In [10]:
least_frq = element_frq.index[-1]
least_frq

'i'

In [11]:
new_strig = sr.replace(' ', least_frq)
new_strig

'abcidefiabcdefiicd'

## ??34- Write a Pandas program to compute the autocorrelations of a given numeric series.

In [ ]:
"""
From Wikipedia:
Autocorrelation, also known as serial correlation, is the correlation of a signal with a delayed copy of itself as a function of delay. Informally, it is the similarity between observations as a function of the time lag between them.
Sample Output:
Original series:
0 13.207262
1 4.098685
2 -1.435534
3 13.626760
... 13 -2.346193
14 17.873884
dtype: float64
Autocorrelations of the said series:
[-0.38, 0.1, -0.43, 0.03, 0.35, -0.2, 0.04, -0.59, 0.34, 0.11]
"""

In [13]:
n_array = np.random.random_sample()

In [20]:
n_array = np.random.normal(1, 10, 15)

In [21]:
n_array

array([ 11.77420365, -19.25472829,  12.73843155,  18.30083949,
         7.75616722,  -0.47534076,  17.51913274,  13.54143298,
        -1.14637672,   3.67126492,   2.42992922,  -3.98523425,
        -5.90123274,  10.0996871 , -15.55804247])

In [23]:
pd_sr = pd.Series(data=n_array)

In [24]:
pd_sr.autocorr

<bound method Series.autocorr of 0     11.774204
1    -19.254728
2     12.738432
3     18.300839
4      7.756167
5     -0.475341
6     17.519133
7     13.541433
8     -1.146377
9      3.671265
10     2.429929
11    -3.985234
12    -5.901233
13    10.099687
14   -15.558042
dtype: float64>

## !!35- Write a Pandas program to create a TimeSeries to display all the Sundays of given year. 

In [ ]:
"""
Sample Output:
All Sundays of 2019:
0 2020-01-05
1 2020-01-12
2 2020-01-19
3 2020-01-26
4 2020-02-02
5 2020-02-09
..... 48 2020-12-06
49 2020-12-13
50 2020-12-20
51 2020-12-27
dtype: datetime64[ns]
"""

In [ ]:
pd.date_range('2020-01-01', )

[offset alias- freq attribute] (https://pandas.pydata.org/pandas-docs/stable/user_guide/timeseries.html#offset-aliases)


In [26]:
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
result

0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]

## 36- Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe. 

In [ ]:
"""
Sample Output:
index 0
0 A 0
1 B 1
2 C 2
3 D 3
4 E 4
"""

In [28]:
sr = ['a','b','c','d','e']
pd_sr = pd.Series(data=sr)

In [29]:
pd_sr

0    a
1    b
2    c
3    d
4    e
dtype: object

In [37]:
pd.DataFrame(data=pd_sr).reset_index()

index  0
0      0  a
1      1  b
2      2  c
3      3  d
4      4  e

## 37- Write a Pandas program to stack two given series vertically and horizontally. 

In [ ]:
"""
Sample Output:
Original Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
dtype: int64
0 p
1 q
2 r
3 s
4 t
5 u
6 v
7 w
8 x
9 y
dtype: object
Stack two given series vertically and horizontally:
0 1
0 0 p
1 1 q
2 2 r
3 3 s
4 4 t
5 5 u
6 6 v
7 7 w
8 8 x
9 9 y
"""

In [40]:
sr = 'pqrstuvwxy'
sr = list(sr)
sr

['p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y']

In [41]:
sr1 = [0,1,2,3,4,5,6,7,8,9]

In [43]:
pd_sr = pd.Series(data=sr)
pd_sr1 = pd.Series(data=sr1)

In [46]:
pd.concat([pd_sr, pd_sr1], axis=1)

0  1
0  p  0
1  q  1
2  r  2
3  s  3
4  t  4
5  u  5
6  v  6
7  w  7
8  x  8
9  y  9

## 38- Write a Pandas program to check the equality of two given series.

In [47]:
"""
Original Series:
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
0 1
1 8
2 7
3 5
4 6
5 5
6 3
7 4
8 7
9 1
dtype: int64
Check 2 series are equal or not?
0 True
1 True
2 True
3 True
4 True
5 True
6 True
7 True
8 True
9 True
dtype: bool
"""

'\nOriginal Series:\n0 1\n1 8\n2 7\n3 5\n4 6\n5 5\n6 3\n7 4\n8 7\n9 1\ndtype: int64\n0 1\n1 8\n2 7\n3 5\n4 6\n5 5\n6 3\n7 4\n8 7\n9 1\ndtype: int64\nCheck 2 series are equal or not?\n0 True\n1 True\n2 True\n3 True\n4 True\n5 True\n6 True\n7 True\n8 True\n9 True\ndtype: bool\n'

In [48]:
sr1 = [1,8,7,5,6,5,3,4,7,1]
sr2 = [1,8,7,5,6,5,3,4,7,1]

In [49]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

In [53]:
pd_sr1 == pd_sr2

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

## 39- Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given

In [ ]:
"""
Original Series:
0 1
1 3
2 7
3 12
4 88
5 23
6 3
7 1
8 9
9 0
dtype: int64
Index of the first occurrence of the smallest and largest value of the said series:
9
4
"""

In [4]:
sr = [1,3,7,12,88,23,3,1,9,0,]

In [5]:
pd_sr = pd.Series(data=sr)

In [6]:
pd_sr.sort_values(inplace=True)

In [11]:
pd_sr

9     0
0     1
7     1
1     3
6     3
2     7
8     9
3    12
5    23
4    88
dtype: int64

In [19]:
pd_sr.head(1).index[0]

9

In [20]:
pd_sr.tail(1).index[0]

4

## ??40- Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

In [ ]:
"""
Original DataFrame:
W X Y Z
0 68.0 78.0 84 86
1 75.0 75.0 94 97
2 86.0 NaN 89 96
3 80.0 80.0 86 72
4 NaN 86.0 86 83
Original Series:
0 68.0
1 75.0
2 86.0
3 80.0
4 NaN
dtype: float64
Check for inequality of the said series & dataframe:
W X Y Z
0 False True True True
1 False False True True
2 False True True True
3 False False True True
4 True True True True
"""

# Fizz Buzz

In [ ]:
def fizzbuzz(value_group, divider_a, divivider_b):

  for value in value_group: 
    if value % divider_a == 0 and value % divivider_b !=0:
      print('fizz')
    if value % divider_a != 0 and value % divivider_b == 0:
      print('buzz')
    if value % divider_a == 0 and value % divivider_b == 0:
      print('fizzbuzz')
    if value % divider_a != 0 and value % divivider_b != 0:
      print(value)

In [ ]:
value_group = list(range(1, 101, 1))  

divider_a = 7
divider_b = 8

fizzbuzz(value_group, divider_a, divider_b)

1
2
3
4
5
6
fizz
buzz
9
10
11
12
13
fizz
15
buzz
17
18
19
20
fizz
22
23
buzz
25
26
27
fizz
29
30
31
buzz
33
34
fizz
36
37
38
39
buzz
41
fizz
43
44
45
46
47
buzz
fizz
50
51
52
53
54
55
fizzbuzz
57
58
59
60
61
62
fizz
buzz
65
66
67
68
69
fizz
71
buzz
73
74
75
76
fizz
78
79
buzz
81
82
83
fizz
85
86
87
buzz
89
90
fizz
92
93
94
95
buzz
97
fizz
99
100
