<a href="https://colab.research.google.com/github/KeysiYTS/pandas-exercises/blob/main/Python_Pandas_Data_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[W3 Resources](https://www.w3resource.com/python-exercises/pandas/index-data-series.php)


In [1]:
import pandas as pd
import numpy as np

# OCT-01-2021

## 1- Write a Pandas program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

oct-01-2021

In [ ]:
pds = pd.Series(data=[1,2,3,4,5])
print(pds)

0    1
1    2
2    3
3    4
4    5
dtype: int64


##2- Write a Pandas program to convert a Panda module Series to Python list and it's type

In [ ]:
python_list = pds.to_list()
print(python_list)

[1, 2, 3, 4, 5]


In [ ]:
print(type(pds.to_list()))

<class 'list'>


## 3- Write a Pandas program to add, subtract, multiple and divide two Pandas Series. 


In [ ]:
# Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [ ]:
pds1 = pd.Series(data=[2, 4, 6, 8, 10])
pds2 = pd.Series(data=[1, 3, 5, 7, 9])

In [ ]:
pds_add = pds1.add(pds2, axis=0) # or pds1 + pds2
print(pds_add)

0     3
1     7
2    11
3    15
4    19
dtype: int64


In [ ]:
pds_sub = pds1.subtract(pds2, axis=0) # or pds1 - pds2
print(pds_sub)

0    1
1    1
2    1
3    1
4    1
dtype: int64


In [ ]:
pds_mul = pds1.multiply(pds2, axis=0) # or pds1 * pds2
print(pds_mul)

0     2
1    12
2    30
3    56
4    90
dtype: int64


In [ ]:
pds_div = pds1.divide(pds2, axis=0) # or pds1/pds2
print(pds_div)

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


## 4- Write a Pandas program to compare the elements of the two Pandas Series.


In [ ]:
#Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [ ]:
pds1 = pd.Series(data=[2, 4, 6, 8, 10])
pds2 = pd.Series(data=[1, 3, 5, 7, 10])

In [ ]:
print(pds1 == pds2)

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [ ]:
print(pds1 > pds2)

0     True
1     True
2     True
3     True
4    False
dtype: bool


In [ ]:
print(pds1 < pds2)

0    False
1    False
2    False
3    False
4    False
dtype: bool


## 5- Write a Pandas program to convert a dictionary to a Pandas series. 

In [ ]:
"""
Sample Series:
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
Converted series:
a 100
b 200
c 300
d 400
e 800
dtype: int64
"""

"\nSample Series:\nOriginal dictionary:\n{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}\nConverted series:\na 100\nb 200\nc 300\nd 400\ne 800\ndtype: int64\n"

In [ ]:
pds = pd.Series(data={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})
print(pds)

a    100
b    200
c    300
d    400
e    800
dtype: int64


## 6- Write a Pandas program to convert a NumPy array to a Pandas series.

In [ ]:
"""
Sample Series:
NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0 10
1 20
2 30
3 40
4 50
dtype: int64
"""

'\nSample Series:\nNumPy array:\n[10 20 30 40 50]\nConverted Pandas series:\n0 10\n1 20\n2 30\n3 40\n4 50\ndtype: int64\n'

In [ ]:
npa = np.array([10, 20, 30, 40, 50])
print(npa)
print(type(npa))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
pdn = pd.Series(data=npa)
print(pdn)

0    10
1    20
2    30
3    40
4    50
dtype: int64


## !!7- Write a Pandas program to change the data type of given a column or a Series. 

In [ ]:
"""
Sample Series:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Change the said data type to numeric:
0 100.00
1 200.00
2 NaN
3 300.12
4 400.00
dtype: float64
"""

'\nSample Series:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nChange the said data type to numeric:\n0 100.00\n1 200.00\n2 NaN\n3 300.12\n4 400.00\ndtype: float64\n'

In [ ]:
pds = pd.Series(data=[100,200,'python',300.12,400])
print(pds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [ ]:
pd.to_numeric(pds, errors='coerce')

0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

## 8- Write a Pandas program to convert the first column of a DataFrame as a Series.

In [ ]:
"""
Sample Output:
Original DataFrame
col1 col2 col3
0 1 4 7
1 2 5 5
2 3 6 8
3 4 9 12
4 7 5 1
5 11 0 11
1st column as a Series:
0 1
1 2
2 3
3 4
4 7
5 11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>
"""

"\nSample Output:\nOriginal DataFrame\ncol1 col2 col3\n0 1 4 7\n1 2 5 5\n2 3 6 8\n3 4 9 12\n4 7 5 1\n5 11 0 11\n1st column as a Series:\n0 1\n1 2\n2 3\n3 4\n4 7\n5 11\nName: col1, dtype: int64\n<class 'pandas.core.series.Series'>\n"

In [ ]:
arrays = [[1 ,4 ,7], [2 ,5 ,5],
          [3 ,6 ,8], [4 ,9 ,12],
          [7 ,5 ,1], [11, 0, 11]]

In [ ]:
pdf = pd.DataFrame(data=arrays, columns=['col1','col2','col3'])
pdf

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [ ]:
print(pdf['col1'])
print(type(pdf['col1']))

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>


## !!9- Write a Pandas program to convert a given Series to an array.

In [ ]:
"""
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Series to an array
['100' '200' 'python' '300.12' '400']
"""

"\nSample Output:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nSeries to an array\n['100' '200' 'python' '300.12' '400']\n"

In [ ]:
pds = pd.Series(data=[100,200,'python',300.12,400])
print(pds)

0       100
1       200
2    python
3    300.12
4       400
dtype: object


In [ ]:
pds.to_list()

[100, 200, 'python', 300.12, 400]

## ?10- Write a Pandas program to convert Series of lists to one Series.

In [ ]:
"""
Sample Output:
Original Series of list
0 [Red, Green, White]
1 [Red, Black]
2 [Yellow]
dtype: object
One Series
0 Red
1 Green
2 White
3 Red
4 Black
5 Yellow
dtype: object
"""

'\nSample Output:\nOriginal Series of list\n0 [Red, Green, White]\n1 [Red, Black]\n2 [Yellow]\ndtype: object\nOne Series\n0 Red\n1 Green\n2 White\n3 Red\n4 Black\n5 Yellow\ndtype: object\n'

## 11 - Write a Pandas program to sort a given Series

In [ ]:
"""
Sample Output:
Original Data Series: 
0 100
1 200
2 python
3 300.12
4 400
dtype: object
0 100
1 200
3 300.12
4 400
2 python
dtype: object
"""

'\nSample Output:\nOriginal Data Series: \n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\n0 100\n1 200\n3 300.12\n4 400\n2 python\ndtype: object\n'

In [ ]:
pds = pd.Series(['100', '200', 'python', '300.12', '400'])
pds

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [ ]:
pds.sort_values()

0       100
1       200
3    300.12
4       400
2    python
dtype: object

# OCT-02-2021

## !!12- Write a Pandas program to add some data to an existing Series. 




In [ ]:
"""
Sample Output:
Original Data Series:
0 100
1 200
2 python
3 300.12
4 400
dtype: object
Data Series after adding some data:
0 100
1 200
2 python
3 300.12
4 400
0 500
1 php
dtype: object
"""

'\nSample Output:\nOriginal Data Series:\n0 100\n1 200\n2 python\n3 300.12\n4 400\ndtype: object\nData Series after adding some data:\n0 100\n1 200\n2 python\n3 300.12\n4 400\n0 500\n1 php\ndtype: object\n'

In [ ]:
pds = pd.Series(['100', '200', 'python', '300.12', '400'])
pds

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [ ]:
pds.append(to_append=pd.Series(['500', 'php']))

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

## 13- Write a Pandas program to create a subset of a given series based on value and condition.

In [ ]:
"""
Sample Output:
Original Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
10 10
dtype: int64
Subset of the above Data Series:
0 0
1 1
2 2
3 3
4 4
5 5
dtype: int64
"""

'\nSample Output:\nOriginal Data Series:\n0 0\n1 1\n2 2\n3 3\n4 4\n5 5\n6 6\n7 7\n8 8\n9 9\n10 10\ndtype: int64\nSubset of the above Data Series:\n0 0\n1 1\n2 2\n3 3\n4 4\n5 5\ndtype: int64\n'

In [ ]:
var = [0,1,2,3,4,5,6,7,8,9,10]

In [ ]:
pds = pd.Series(data=var)
pds

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

In [ ]:
pds.iloc[0:6]

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

## !!14- Write a Pandas program to change the order of index of a given series. 

In [ ]:
"""
Sample Output:
Original Data Series:
A 1
B 2
C 3
D 4
E 5
dtype: int64
Data Series after changing the order of index:
B 2
A 1
C 3
D 4
E 5
dtype: int64
"""

'\nSample Output:\nOriginal Data Series:\nA 1\nB 2\nC 3\nD 4\nE 5\ndtype: int64\nData Series after changing the order of index:\nB 2\nA 1\nC 3\nD 4\nE 5\ndtype: int64\n'

In [ ]:
var = [1,2,3,4,5]
idx = ['A', 'B', 'C', 'D', 'E']

In [ ]:
pds = pd.Series(var, index=idx)
pds

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [ ]:
idx2 = ['B', 'A', 'C', 'D', 'E']

In [ ]:
pds.reindex(index=idx2)

B    2
A    1
C    3
D    4
E    5
dtype: int64

## 15- Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [ ]:
"""
Sample Output:
Original Data Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 5
10 3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565
"""

'\nSample Output:\nOriginal Data Series:\n0 1\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n7 8\n8 9\n9 5\n10 3\ndtype: int64\nMean of the said Data Series:\n4.818181818181818\nStandard deviation of the said Data Series:\n2.522624895547565\n'

In [ ]:
var = [1,2,3,4,5,6,7,8,9,5,3]

In [ ]:
pds = pd.Series(data=var)

In [ ]:
pds.mean()

4.818181818181818

In [ ]:
pds.std()

2.522624895547565

# OCT-07-2021

### !!16- Write a Pandas program to get the items of a given series not present in another given serieS

In [ ]:
"""
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of sr1 not present in sr2:
0 1
2 3
4 5
dtype: int64
"""

'\nOriginal Series:\nsr1:\n0 1\n1 2\n2 3\n3 4\n4 5\ndtype: int64\nsr2:\n0 2\n1 4\n2 6\n3 8\n4 10\ndtype: int64\nItems of sr1 not present in sr2:\n0 1\n2 3\n4 5\ndtype: int64\n'

In [ ]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]

In [ ]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

In [ ]:
pd_sr1[~pd_sr1.isin(pd_sr2)]

0    1
2    3
4    5
dtype: int64

In [ ]:
pd_sr1[pd_sr1.isin(pd_sr2) == False]

0    1
2    3
4    5
dtype: int64

## ?17- Write a Pandas program to get the items which are not common of two given series.

In [ ]:
"""
Sample Output:
Original Series:
sr1:
0 1
1 2
2 3
3 4
4 5
dtype: int64
sr2:
0 2
1 4
2 6
3 8
4 10
dtype: int64
Items of a given series not present in another given series:
0 1
2 3
4 5
5 6
6 8
7 10
dtype: int64
"""

'\nSample Output:\nOriginal Series:\nsr1:\n0 1\n1 2\n2 3\n3 4\n4 5\ndtype: int64\nsr2:\n0 2\n1 4\n2 6\n3 8\n4 10\ndtype: int64\nItems of a given series not present in another given series:\n0 1\n2 3\n4 5\n5 6\n6 8\n7 10\ndtype: int64\n'

In [ ]:
sr1 = [1,2,3,4,5]
sr2 = [2,4,6,8,10]

In [ ]:
pd_sr1 = pd.Series(data=sr1)
pd_sr2 = pd.Series(data=sr2)

## !!18- Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 3.000938
1 11.370722
2 14.612143
3 8.990256
4 13.925283
5 12.056875
.... 17 14.118931
18 8.247458
19 5.526727
dtype: float64
Minimum, 25th percentile, median, 75th, and maximum of a given series:
[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]
"""

'\nSample Output:\nOriginal Series:\n0 3.000938\n1 11.370722\n2 14.612143\n3 8.990256\n4 13.925283\n5 12.056875\n.... 17 14.118931\n18 8.247458\n19 5.526727\ndtype: float64\nMinimum, 25th percentile, median, 75th, and maximum of a given series:\n[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]\n'

In [ ]:
sr = [3.000938,11.370722,14.612143,8.990256,13.925283,12.056875]

In [ ]:
pd_sr = pd.Series(data=sr)
pd_sr

0     3.000938
1    11.370722
2    14.612143
3     8.990256
4    13.925283
5    12.056875
dtype: float64

In [ ]:
print(pd_sr.min())
print(pd_sr.median())
print(pd_sr.max())

3.000938
11.7137985
14.612143


In [ ]:
np.percentile(pd_sr, q=[0,25,50,100])

array([ 3.000938 ,  9.5853725, 11.7137985, 14.612143 ])

In [ ]:
result = np.percentile(pd_sr, q=[0,25,50,75,100])
print(f'Min. value: {result[0]}')
print(f"25th percentile: {result[1]}")
print(f"median: {result[2]}")
print(f"75th percentile: {result[3]}")
print(f"max value: {result[4]}")

Min. value: 3.000938
25th percentile: 9.5853725
median: 11.7137985
75th percentile: 13.458181
max value: 14.612143


# OCT-08-2021


## 19- Write a Pandas program to calculate the frequency counts of each unique value of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 1
1 7
2 1
3 6
4 9
5 1
... 29 2
30 9
31 1
32 2
33 9
34 2
35 9
36 0
37 0
38 4
39 8
dtype: object
Frequency of each unique value of the said series.
0 9
2 7
9 6
1 5
6 3
8 3
7 3
3 2
4 1
5 1
dtype: int64s
"""

'\nSample Output:\nOriginal Series:\n0 1\n1 7\n2 1\n3 6\n4 9\n5 1\n... 29 2\n30 9\n31 1\n32 2\n33 9\n34 2\n35 9\n36 0\n37 0\n38 4\n39 8\ndtype: object\nFrequency of each unique value of the said series.\n0 9\n2 7\n9 6\n1 5\n6 3\n8 3\n7 3\n3 2\n4 1\n5 1\ndtype: int64s\n'

In [ ]:
sr = [1,16,5,1,8,4,18,4,8,7,9,4,5,1,6,8,76,1,56,49,8]

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
pd_sr.value_counts() 

8     4
1     4
4     3
5     2
56    1
18    1
49    1
16    1
76    1
9     1
7     1
6     1
dtype: int64

## 20- Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series. 

In [ ]:
sr = np.random.randint(1,20,[20])

In [ ]:
pd_sr = pd.Series(data=sr)

In [ ]:
value_frequency = pd_sr.value_counts()
value_frequency

13    3
10    3
3     3
18    2
8     2
4     2
2     2
1     2
11    1
dtype: int64

In [ ]:
value_frequency.replace()

13    3
10    3
3     3
18    2
8     2
4     2
2     2
1     2
11    1
dtype: int64

In [ ]:
pd_sr[pd_sr.isin(value_frequency)]

2     3
8     2
9     3
10    1
13    1
15    3
18    2
dtype: int64

In [ ]:
pd_sr

0     13
1     11
2      3
3      4
4      4
5     10
6      8
7     13
8      2
9      3
10     1
11    18
12    10
13     1
14    13
15     3
16    10
17     8
18     2
19    18
dtype: int64

In [ ]:
value_frequency

13    3
10    3
3     3
18    2
8     2
4     2
2     2
1     2
11    1
dtype: int64

# OCT-11-2021


## !!21- Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series

In [ ]:
"""
Original Series:
0 1
1 9
2 8
3 6
4 9
5 7
6 1
7 1
8 1
dtype: int64
Positions of numbers that are multiples of 5:
[]
"""

In [ ]:
sr = [9,1,8,5,9,7,1,1,1]

In [ ]:
pd_sr = pd.Series(data=sr)
pd_sr

0    9
1    1
2    8
3    5
4    9
5    7
6    1
7    1
8    1
dtype: int64

Find the indices of array elements that are non-zero, grouped by element.

In [ ]:
pd_sr[pd_sr%5==0].index

Int64Index([3], dtype='int64')

OR

In [ ]:
values = np.random.randint(1,20,15)
pd_np_sr = pd.Series(values)
print(pd_np_sr)
print(np.argwhere(values%5==0))

0      8
1      3
2     19
3     19
4      9
5      8
6     10
7      4
8      7
9     18
10     1
11    16
12    10
13     5
14    15
dtype: int64
[[ 6]
 [12]
 [13]
 [14]]


array([[0],
       [1],
       [7]])

## !!22- Write a Pandas program to extract items at given positions of a given series.

In [ ]:
"""
Sample Output:
Original Series:
0 2
1 3
2 9
3 0
4 2
5 3
... 19 0
20 2
21 3
dtype: object
Extract items at given positions of the said series:
0 2
2 9
6 8
11 0
21 3
dtype: object
"""

In [ ]:
values = np.random.randint(1, 20, 15)

In [ ]:
pd_sr = pd.Series(values)

In [ ]:
pd_sr.take([0,2,6,11])

0     12
2      6
6     19
11    16
dtype: int64

In [ ]:
pd_sr[0:12]

0     12
1      7
2      6
3      1
4      8
5     11
6     19
7     15
8     19
9      8
10    18
11    16
dtype: int64

### 23. Write a Pandas program to get the positions of items of a given series in another given series.

In [ ]:
"""
Sample Output:
Original Series:
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
dtype: int64
0 1
1 3
2 5
3 7
4 10
dtype: int64
Positions of items of series2 in series1:
[0, 2, 4, 6, 9]
"""

'\nSample Output:\nOriginal Series:\n0 1\n1 2\n2 3\n3 4\n4 5\n5 6\n6 7\n7 8\n8 9\n9 10\ndtype: int64\n0 1\n1 3\n2 5\n3 7\n4 10\ndtype: int64\nPositions of items of series2 in series1:\n[0, 2, 4, 6, 9]\n'

In [ ]:
sr1 = [1,2,3,4,5,6,7,8,9,10]
sr2 = [1,3,5,7]

In [ ]:
pd_sr1 = pd.Series(sr1)
pd_sr2 = pd.Series(sr2)